### ISSUE TITLE
Printing

### ISSUE THREAD

**Issue by razvan-panda** [vickychijwani/closer.js#14]
Is there a way to print stuff in the [Parser Demo](http://vickychijwani.github.io/closer.js/) for example or in Code Combat?

**Comment by vickychijwani** [comment]
You can use `(.log console "hello," "world!")` or `(println "hello," "world!")` to print to the JavaScript console in your browser. (But there was a bug in `println` that caused it to fail in browsers; [I've fixed it now](https://github.com/vickychijwani/closer.js/commit/ed9935003251a353e55678004611c82870a10e1c)).

**Comment by razvan-panda** [comment]
Trying with `(.log console "test")` in CodeCombat it throws a: `Line 1: ReferenceError: console is not defined` error.

And `Simple loop not implemented for Clojure` error in console "https://codecombat.com/javascripts/aether.js:2410"

**Comment by vickychijwani** [comment]
CodeCombat doesn't expose the `console` object to user code [1], I guess, so println won't work either (even after my fix). But they do have a `say` function that prints stuff on the screen, in-game, I believe.

https://github.com/codecombat/aether/blob/7f8a4a9d43b7305e6cc6a42476d739f37b1a6c26/src/protectBuiltins.coffee

**Comment by razvan-panda** [comment]
Yes, that would be a good workaround for CodeCombat, thank you.

**Comment by vickychijwani** [comment]
Also, just a note: the `Simple loop not implemented for Clojure` message seems unrelated to this. As of now that message will get printed for *any* Clojure code in CodeCombat.
