### ISSUE TITLE
Function values

### ISSUE THREAD

**Issue by razvan-panda** [vickychijwani/closer.js#15]
Are function values not supported?

Here is a very simple example which does not work:

    (defn runit [f]
      (f))

    (defn run []
      (runit #(.moveRight this)))

    (run)

In browser console there is a `Simple loop not implemented for Clojure` at https://codecombat.com/javascripts/aether.js error displayed when run.

Same problem with:

    (defn runit [f]
      (f))

    (defn run []
      (runit (fn [] (.moveRight this))))

    (run)

Or just:

    (defn runit [f]
      (f))

    (defn afunction []
      (.moveRight this))

    (defn run []
      (runit afunction))

    (run)

**Comment by vickychijwani** [comment]
This should work, ideally. This code works in the parser demo:

```clojure
(defn runit [f]
  (f))

(defn run []
  (runit #(.log console "running")))

(run)
```

It may be a consequence of codecombat/aether#143, as you noted in the other issue, I'm not sure (I'm not very familiar with how Aether works internally).

**Comment by razvan-panda** [comment]
Tested in CodeCombat, this works:

    (.say this "Function value test")

This does not work:

    (defn runit [f]
      (f))

    (defn run []
      (runit #(.say this "Function value test")))

    (run)

**Comment by razvan-panda** [comment]
@vickychijwani Tried the code you mentioned in the [parser demo](http://vickychijwani.github.io/closer.js/) and it did not seem to work:

![](http://i.imgur.com/Q51Ss0O.png)

**Comment by razvan-panda** [comment]
Even doing only `(.log console "running")` does not print anything at all.

**Comment by vickychijwani** [comment]
Sorry, forgot to mention the output will go to your web browser's Javascript console, since we're calling `console.log` here.

**Comment by razvan-panda** [comment]
Thank you, just dawned to me after I posted. :)

**Comment by razvan-panda** [comment]
The function as value call, works correctly as you said.

**Comment by vickychijwani** [comment]
Sure, happy to help :)

**Comment by nwinter** [comment]
Sounds like this may have been a CodeCombat bug and not a closer.js bug?

**Comment by vickychijwani** [comment]
Yeah, probably. I guess I can close this here.
